# ============================================
# CashFlow v4.0 - Docker Compose Configuration
# For Docker Desktop on Windows
# ============================================

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: cashflow-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: cashflow2025
      MONGO_INITDB_DATABASE: cashflow
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cashflow-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: cashflow-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:cashflow2025@mongodb:27017/cashflow?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-cashflow-secret-key-2025-change-in-production}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - cashflow-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React + Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: cashflow-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cashflow-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  cashflow-network:
    driver: bridge
    name: cashflow-network

volumes:
  mongodb_data:
    driver: local
    name: cashflow-mongodb-data
  mongodb_config:
    driver: local
    name: cashflow-mongodb-config
